insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (1, 0, 64, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', '2019-02-03', 14);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (2, 0, 47, 'Ut at dolor quis odio consequat varius. Integer ac leo.', '2019-10-09', 41);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (3, 0, 17, 'Duis aliquam convallis nunc.', '2019-01-14', 59);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (4, 0, 24, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', '2019-05-20', 95);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (5, 0, 51, 'In quis justo. Maecenas rhoncus aliquam lacus.', '2019-10-18', 23);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (6, 0, 43, 'Donec semper sapien a libero. Nam dui.', '2019-04-08', 31);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (7, 0, 95, 'Nulla suscipit ligula in lacus.', '2019-10-31', 29);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (8, 0, 25, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2019-06-18', 12);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (9, 0, 34, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2019-07-09', 90);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (10, 0, 74, 'Phasellus in felis.', '2019-04-21', 83);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (11, 0, 31, 'Nullam varius. Nulla facilisi.', '2019-03-07', 31);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (12, 0, 22, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2019-04-05', 24);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (13, 0, 15, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2019-09-05', 42);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (14, 0, 64, 'Morbi porttitor lorem id ligula.', '2019-06-06', 4);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (15, 0, 14, 'Quisque porta volutpat erat.', '2019-07-30', 5);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (16, 0, 14, 'Aliquam non mauris.', '2019-01-21', 95);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (17, 0, 24, 'Integer a nibh.', '2019-05-03', 98);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (18, 0, 57, 'Duis aliquam convallis nunc.', '2019-07-27', 67);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (19, 0, 38, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2018-12-14', 81);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (20, 0, 53, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2019-10-01', 15);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (21, 0, 52, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2019-05-02', 8);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (22, 0, 35, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2019-09-09', 9);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (23, 0, 16, 'Pellentesque ultrices mattis odio.', '2019-04-28', 66);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (24, 0, 93, 'Suspendisse accumsan tortor quis turpis.', '2018-12-15', 78);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (25, 0, 96, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2018-12-30', 38);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (26, 0, 46, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', '2019-04-12', 73);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (27, 0, 83, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2019-02-05', 2);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (28, 0, 85, 'Vivamus vestibulum sagittis sapien.', '2019-04-13', 47);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (29, 0, 19, 'Suspendisse ornare consequat lectus.', '2019-07-28', 13);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (30, 0, 14, 'In quis justo.', '2019-01-17', 56);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (31, 0, 35, 'Ut tellus.', '2019-06-02', 51);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (32, 0, 21, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2019-09-25', 99);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (33, 0, 44, 'Integer ac leo. Pellentesque ultrices mattis odio.', '2019-08-31', 71);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (34, 0, 18, 'Duis consequat dui nec nisi volutpat eleifend.', '2019-09-10', 2);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (35, 0, 29, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', '2019-11-13', 71);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (36, 0, 36, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2019-07-14', 67);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (37, 0, 59, 'Nulla nisl. Nunc nisl.', '2019-05-05', 20);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (38, 0, 24, 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2019-06-25', 60);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (39, 0, 20, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '2019-10-01', 61);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (40, 0, 91, 'In hac habitasse platea dictumst.', '2019-02-06', 100);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (41, 0, 14, 'Nulla tellus. In sagittis dui vel nisl.', '2019-06-14', 57);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (42, 0, 84, 'Proin eu mi.', '2019-05-18', 100);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (43, 0, 50, 'vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', '2019-07-06', 79);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (44, 0, 8, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', '2018-12-24', 29);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (45, 0, 59, 'In eleifend quam a odio. In hac habitasse platea dictumst.', '2019-07-26', 91);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (46, 0, 66, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', '2019-06-28', 54);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (47, 0, 91, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2019-04-24', 79);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (48, 0, 55, 'Aliquam non mauris. Morbi non lectus.', '2019-11-04', 95);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (49, 0, 42, 'Praesent lectus.', '2019-04-22', 94);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (50, 0, 21, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2019-05-26', 59);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (51, 0, 100, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '2019-02-26', 34);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (52, 0, 56, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', '2019-02-13', 33);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (53, 0, 6, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2019-06-17', 49);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (54, 0, 97, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2019-02-02', 92);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (55, 0, 36, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2019-06-09', 77);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (56, 0, 44, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2019-04-22', 11);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (57, 0, 44, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2019-08-06', 94);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (58, 0, 48, 'Etiam faucibus cursus urna. Ut tellus.', '2019-02-11', 44);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (59, 0, 22, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', '2019-06-29', 47);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (60, 0, 90, 'Praesent id massa id nisl venenatis lacinia.', '2019-03-22', 91);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (61, 0, 31, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2019-06-07', 24);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (62, 0, 14, 'Quisque porta volutpat erat.', '2019-07-05', 6);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (63, 0, 19, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2019-08-07', 21);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (64, 0, 47, 'Pellentesque ultrices mattis odio. Donec vitae nisi.', '2019-10-25', 65);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (65, 0, 93, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2019-10-20', 73);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (66, 0, 54, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '2018-12-04', 44);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (67, 0, 41, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2019-09-14', 14);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (68, 0, 96, 'Nullam varius.', '2019-09-19', 48);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (69, 0, 87, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2019-01-07', 45);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (70, 0, 6, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '2018-11-30', 41);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (71, 0, 65, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2019-07-18', 29);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (72, 0, 60, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2018-11-30', 16);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (73, 0, 51, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2019-03-04', 96);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (74, 0, 73, 'Ut at dolor quis odio consequat varius. Integer ac leo.', '2019-01-02', 12);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (75, 0, 99, 'Donec quis orci eget orci vehicula condimentum.', '2019-06-09', 19);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (76, 0, 43, 'In hac habitasse platea dictumst.', '2019-11-11', 69);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (77, 0, 23, 'Suspendisse potenti.', '2019-05-21', 72);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (78, 0, 22, 'Praesent blandit lacinia erat.', '2019-02-22', 95);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (79, 0, 78, 'In sagittis dui vel nisl.', '2019-08-21', 15);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (80, 0, 20, 'Vivamus vel nulla eget eros elementum pellentesque.', '2019-03-08', 13);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (81, 0, 48, 'Donec ut dolor.', '2019-08-06', 84);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (82, 0, 60, 'Etiam faucibus cursus urna.', '2019-07-15', 76);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (83, 0, 92, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2019-04-29', 15);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (84, 0, 12, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2019-02-24', 96);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (85, 0, 75, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2019-04-24', 67);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (86, 0, 45, 'Nam dui.', '2018-12-23', 23);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (87, 0, 94, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', '2019-05-22', 7);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (88, 0, 25, 'Nunc rhoncus dui vel sem. Sed sagittis.', '2019-11-16', 55);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (89, 0, 79, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2019-04-18', 62);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (90, 0, 41, 'Quisque id justo sit amet sapien dignissim vestibulum.', '2019-05-04', 79);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (91, 0, 36, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2018-12-27', 87);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (92, 0, 25, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2018-12-05', 49);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (93, 0, 26, 'Donec ut mauris eget massa tempor convallis.', '2019-01-30', 41);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (94, 0, 49, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', '2019-10-20', 39);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (95, 0, 33, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2019-07-14', 39);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (96, 0, 22, 'Ut at dolor quis odio consequat varius.', '2019-07-03', 90);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (97, 0, 9, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2019-11-02', 34);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (98, 0, 79, 'Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2019-03-11', 56);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (99, 0, 26, 'Nam nulla.', '2019-07-30', 63);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (100, 0, 16, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2019-02-12', 87);
