insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (101, 61, 69, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2018-12-07', 95);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (102, 44, 80, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', '2019-05-04', 82);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (103, 7, 5, 'Donec ut mauris eget massa tempor convallis.', '2019-03-22', 2);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (104, 6, 62, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '2019-09-15', 99);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (105, 68, 75, 'Nam nulla.', '2019-08-04', 15);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (106, 57, 82, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', '2019-02-28', 69);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (107, 2, 30, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '2019-04-01', 39);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (108, 15, 66, 'Sed ante.', '2019-05-15', 11);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (109, 92, 94, 'Aliquam non mauris. Morbi non lectus.', '2018-12-02', 17);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (110, 93, 89, 'Donec ut mauris eget massa tempor convallis.', '2019-01-27', 72);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (111, 34, 15, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', '2019-05-16', 29);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (112, 81, 31, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2019-03-29', 45);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (113, 44, 59, 'In hac habitasse platea dictumst.', '2019-07-02', 72);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (114, 47, 46, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '2019-09-05', 78);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (115, 48, 27, 'Nullam molestie nibh in lectus.', '2019-05-14', 82);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (116, 70, 2, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2019-08-26', 21);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (117, 47, 86, 'Suspendisse potenti.', '2018-12-28', 28);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (118, 20, 51, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', '2019-05-03', 84);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (119, 36, 69, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', '2019-07-29', 59);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (120, 91, 68, 'In quis justo.', '2019-05-27', 100);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (121, 10, 31, 'Nam nulla.', '2019-01-03', 34);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (122, 39, 35, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2019-07-20', 10);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (123, 52, 22, 'Nunc purus. Phasellus in felis.', '2019-02-08', 52);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (124, 92, 50, 'Suspendisse accumsan tortor quis turpis.', '2019-03-07', 21);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (125, 86, 50, 'Vivamus tortor.', '2019-06-03', 62);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (126, 31, 33, 'Nunc rhoncus dui vel sem.', '2019-01-12', 13);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (127, 29, 34, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2019-09-30', 87);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (128, 12, 10, 'Phasellus id sapien in sapien iaculis congue.', '2019-04-17', 87);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (129, 77, 3, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', '2019-03-30', 19);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (130, 94, 99, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '2019-10-03', 8);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (131, 96, 2, 'Aenean fermentum.', '2019-07-12', 58);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (132, 34, 39, 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2019-10-14', 94);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (133, 99, 76, 'Phasellus in felis. Donec semper sapien a libero.', '2019-10-15', 24);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (134, 84, 5, 'Aenean lectus. Pellentesque eget nunc.', '2019-10-26', 43);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (135, 92, 92, 'Aenean sit amet justo.', '2019-01-24', 16);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (136, 9, 101, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '2019-07-23', 98);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (137, 23, 76, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', '2019-10-06', 52);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (138, 43, 52, 'Aenean fermentum.', '2019-10-18', 27);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (139, 5, 67, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2019-07-24', 96);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (140, 95, 13, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2018-12-09', 99);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (141, 5, 35, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2019-04-15', 46);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (142, 79, 54, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2019-09-17', 98);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (143, 95, 100, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.', '2019-01-19', 29);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (144, 25, 97, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', '2019-04-01', 67);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (145, 4, 26, 'Nam nulla.', '2018-12-06', 89);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (146, 55, 83, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2019-10-05', 90);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (147, 48, 40, 'Nulla suscipit ligula in lacus.', '2019-07-24', 67);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (148, 45, 35, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '2018-12-10', 56);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (149, 20, 29, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2018-12-01', 86);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (150, 90, 53, 'Aenean lectus.', '2019-10-12', 39);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (151, 24, 88, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2019-09-27', 39);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (152, 85, 71, 'Vivamus tortor. Duis mattis egestas metus.', '2019-01-26', 96);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (153, 7, 93, 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2019-03-02', 23);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (154, 58, 41, 'Morbi porttitor lorem id ligula.', '2019-05-15', 53);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (155, 40, 57, 'Etiam justo. Etiam pretium iaculis justo.', '2019-01-02', 18);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (156, 73, 70, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', '2018-11-29', 15);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (157, 48, 101, 'In hac habitasse platea dictumst.', '2019-04-12', 57);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (158, 18, 82, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', '2018-12-14', 43);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (159, 2, 30, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', '2019-05-02', 81);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (160, 77, 32, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2019-03-03', 37);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (161, 54, 68, 'Aliquam sit amet diam in magna bibendum imperdiet.', '2019-09-17', 69);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (162, 33, 79, 'Duis mattis egestas metus. Aenean fermentum.', '2019-04-20', 42);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (163, 99, 98, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2019-04-10', 11);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (164, 19, 84, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', '2019-06-22', 28);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (165, 12, 5, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2019-08-30', 75);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (166, 61, 93, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2019-08-13', 66);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (167, 19, 48, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '2018-11-18', 5);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (168, 49, 49, 'Integer ac neque. Duis bibendum.', '2019-09-12', 89);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (169, 37, 47, 'In quis justo.', '2019-05-24', 18);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (170, 92, 98, 'Curabitur at ipsum ac tellus semper interdum.', '2019-07-21', 85);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (171, 63, 67, 'Suspendisse ornare consequat lectus.', '2018-12-08', 42);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (172, 16, 98, 'Morbi non lectus.', '2019-01-26', 61);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (173, 88, 10, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2019-04-29', 22);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (174, 66, 50, 'In congue.', '2019-05-11', 97);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (175, 47, 97, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2019-02-07', 24);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (176, 56, 97, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2019-06-18', 42);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (177, 51, 48, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2019-04-29', 32);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (178, 61, 84, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2019-10-29', 36);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (179, 51, 37, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2019-03-13', 10);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (180, 81, 83, 'Fusce consequat. Nulla nisl.', '2019-05-02', 92);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (181, 67, 89, 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '2019-03-18', 96);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (182, 39, 31, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2018-12-20', 37);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (183, 12, 12, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', '2019-03-02', 85);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (184, 35, 12, 'Integer ac neque. Duis bibendum.', '2019-08-23', 52);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (185, 6, 84, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2019-10-23', 24);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (186, 91, 40, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '2019-06-06', 29);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (187, 2, 35, 'Pellentesque at nulla.', '2019-09-15', 73);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (188, 98, 19, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2018-12-21', 16);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (189, 3, 60, 'Nulla tempus.', '2019-01-09', 62);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (190, 62, 30, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2019-07-18', 34);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (191, 61, 101, 'Integer tincidunt ante vel ipsum.', '2019-07-05', 86);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (192, 4, 68, 'Aliquam sit amet diam in magna bibendum imperdiet.', '2019-04-15', 19);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (193, 13, 28, 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '2018-12-10', 46);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (194, 1, 18, 'Quisque ut erat. Curabitur gravida nisi at nibh.', '2019-05-02', 95);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (195, 55, 52, 'In hac habitasse platea dictumst.', '2019-10-28', 82);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (196, 41, 66, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2018-11-19', 98);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (197, 75, 89, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2019-11-02', 96);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (198, 48, 36, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2018-11-25', 35);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (199, 97, 9, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', '2019-03-16', 52);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (200, 90, 42, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', '2019-07-07', 88);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (201, 32, 31, 'Phasellus in felis.', '2019-11-17', 24);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (202, 91, 25, 'Praesent blandit lacinia erat.', '2019-05-02', 76);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (203, 16, 30, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '2019-09-30', 95);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (204, 100, 3, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2018-12-12', 3);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (205, 70, 32, 'Cras pellentesque volutpat dui.', '2019-01-14', 53);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (206, 71, 52, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2019-05-28', 94);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (207, 58, 28, 'Nulla nisl.', '2019-06-12', 58);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (208, 23, 29, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2019-03-24', 3);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (209, 31, 66, 'Donec semper sapien a libero.', '2019-10-31', 25);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (210, 1, 8, 'Donec semper sapien a libero.', '2019-10-06', 76);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (211, 2, 35, 'In hac habitasse platea dictumst.', '2019-01-28', 16);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (212, 81, 33, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2019-08-03', 94);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (213, 2, 31, 'Nulla ac enim.', '2018-12-20', 45);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (214, 59, 39, 'Sed ante. Vivamus tortor.', '2019-05-12', 3);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (215, 82, 38, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2019-03-14', 17);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (216, 35, 51, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '2019-06-24', 10);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (217, 82, 90, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2019-06-21', 82);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (218, 94, 97, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2018-12-20', 80);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (219, 11, 67, 'In blandit ultrices enim.', '2019-06-21', 32);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (220, 80, 48, 'In congue.', '2019-03-29', 57);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (221, 75, 96, 'Praesent id massa id nisl venenatis lacinia.', '2019-05-01', 78);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (222, 53, 99, 'Etiam justo.', '2019-10-20', 46);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (223, 89, 70, 'In congue.', '2019-09-11', 87);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (224, 69, 98, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2019-10-12', 46);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (225, 79, 37, 'Duis mattis egestas metus. Aenean fermentum.', '2019-06-16', 65);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (226, 5, 92, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.', '2019-05-03', 51);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (227, 4, 85, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2019-06-28', 49);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (228, 26, 51, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', '2019-06-19', 92);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (229, 85, 26, 'Morbi non quam nec dui luctus rutrum.', '2019-01-24', 20);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (230, 81, 52, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2019-09-18', 57);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (231, 30, 83, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2019-02-04', 89);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (232, 8, 4, 'Aliquam erat volutpat.', '2019-05-11', 94);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (233, 3, 51, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '2019-04-21', 64);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (234, 22, 35, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', '2019-09-22', 9);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (235, 64, 5, 'Cras in purus eu magna vulputate luctus.', '2018-12-02', 93);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (236, 85, 44, 'In sagittis dui vel nisl.', '2019-01-16', 14);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (237, 8, 7, 'Proin interdum mauris non ligula pellentesque ultrices.', '2019-01-21', 18);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (238, 78, 33, 'Nullam porttitor lacus at turpis.', '2019-09-18', 6);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (239, 51, 32, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2018-12-05', 28);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (240, 38, 55, 'Aliquam sit amet diam in magna bibendum imperdiet.', '2019-01-29', 52);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (241, 89, 36, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', '2019-03-22', 83);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (242, 54, 3, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2019-10-30', 39);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (243, 4, 40, 'Aenean fermentum.', '2019-08-02', 57);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (244, 3, 81, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '2019-08-13', 19);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (245, 5, 4, 'Nullam varius. Nulla facilisi.', '2019-08-13', 42);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (246, 31, 53, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2019-10-18', 48);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (247, 8, 41, 'Etiam justo. Etiam pretium iaculis justo.', '2019-06-02', 98);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (248, 98, 88, 'In hac habitasse platea dictumst.', '2019-04-04', 46);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (249, 70, 60, 'Donec dapibus.', '2019-01-15', 4);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (250, 50, 100, 'Vivamus vestibulum sagittis sapien.', '2019-07-23', 48);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (251, 95, 51, 'Morbi a ipsum.', '2019-01-26', 17);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (252, 26, 18, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2019-10-23', 8);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (253, 83, 81, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2019-05-30', 37);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (254, 2, 66, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.', '2019-06-29', 90);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (255, 9, 14, 'Pellentesque ultrices mattis odio.', '2019-06-16', 44);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (256, 74, 4, 'Sed vel enim sit amet nunc viverra dapibus.', '2019-04-17', 27);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (257, 25, 95, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', '2019-05-22', 33);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (258, 62, 39, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2019-10-06', 76);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (259, 32, 6, 'Nam nulla.', '2019-02-04', 78);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (260, 53, 56, 'Duis ac nibh.', '2019-11-04', 78);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (261, 50, 46, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2019-11-13', 97);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (262, 57, 18, 'Integer ac neque.', '2019-11-17', 69);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (263, 2, 70, 'Etiam faucibus cursus urna.', '2019-03-29', 49);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (264, 83, 47, 'Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2019-03-16', 88);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (265, 24, 52, 'Mauris lacinia sapien quis libero.', '2019-09-28', 62);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (266, 92, 70, 'Suspendisse ornare consequat lectus.', '2019-07-16', 53);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (267, 54, 16, 'Aenean auctor gravida sem.', '2019-09-15', 18);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (268, 6, 86, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '2018-11-26', 57);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (269, 3, 98, 'Vivamus vel nulla eget eros elementum pellentesque.', '2019-07-08', 27);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (270, 76, 85, 'Ut at dolor quis odio consequat varius.', '2019-03-11', 2);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (271, 19, 43, 'Phasellus in felis. Donec semper sapien a libero.', '2019-06-20', 2);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (272, 83, 8, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2019-05-29', 23);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (273, 34, 36, 'Nulla tellus.', '2019-05-11', 72);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (274, 30, 87, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2019-06-19', 32);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (275, 58, 65, 'Nullam sit amet turpis elementum ligula vehicula consequat.', '2019-08-16', 72);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (276, 52, 79, 'Duis aliquam convallis nunc.', '2019-01-14', 81);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (277, 12, 55, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', '2019-01-13', 5);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (278, 63, 95, 'Duis bibendum.', '2019-04-01', 13);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (279, 88, 98, 'Nulla mollis molestie lorem.', '2019-09-05', 78);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (280, 92, 101, 'Integer ac leo. Pellentesque ultrices mattis odio.', '2019-03-20', 2);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (281, 48, 30, 'Proin eu mi.', '2019-09-25', 58);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (282, 25, 32, 'Vivamus vestibulum sagittis sapien.', '2018-12-31', 34);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (283, 14, 42, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2018-12-16', 10);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (284, 97, 52, 'Integer a nibh.', '2019-10-10', 23);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (285, 58, 79, 'Suspendisse accumsan tortor quis turpis. Sed ante.', '2019-08-26', 82);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (286, 29, 9, 'In blandit ultrices enim.', '2019-02-16', 24);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (287, 71, 43, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2019-01-20', 12);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (288, 12, 30, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '2019-06-05', 2);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (289, 44, 46, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '2019-05-21', 14);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (290, 53, 95, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '2019-05-11', 81);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (291, 93, 82, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2019-09-20', 3);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (292, 51, 68, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '2019-03-27', 99);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (293, 91, 94, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2019-03-18', 3);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (294, 25, 63, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', '2019-04-12', 25);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (295, 30, 40, 'Sed accumsan felis.', '2019-09-07', 27);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (296, 37, 6, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2019-09-04', 5);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (297, 35, 90, 'Ut at dolor quis odio consequat varius.', '2019-01-18', 51);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (298, 74, 68, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2018-11-29', 80);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (299, 30, 54, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2018-12-22', 19);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (300, 68, 78, 'Mauris lacinia sapien quis libero.', '2019-04-28', 97);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (301, 36, 8, 'Nunc rhoncus dui vel sem.', '2019-07-22', 45);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (302, 26, 49, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2019-08-20', 32);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (303, 83, 22, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2019-06-17', 98);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (304, 97, 22, 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2019-07-21', 97);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (305, 83, 96, 'Vivamus vel nulla eget eros elementum pellentesque.', '2019-10-03', 59);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (306, 1, 8, 'Sed accumsan felis.', '2019-07-07', 96);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (307, 69, 25, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', '2019-05-15', 49);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (308, 15, 5, 'Proin eu mi.', '2019-04-27', 35);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (309, 36, 100, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', '2019-11-10', 89);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (310, 44, 47, 'Ut at dolor quis odio consequat varius.', '2019-09-28', 18);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (311, 92, 45, 'Aenean fermentum.', '2019-04-07', 9);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (312, 12, 88, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '2019-02-02', 18);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (313, 75, 82, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', '2019-05-28', 30);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (314, 78, 7, 'In hac habitasse platea dictumst.', '2019-07-23', 71);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (315, 37, 17, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2019-08-16', 35);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (316, 48, 69, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2019-09-10', 92);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (317, 42, 16, 'Donec ut mauris eget massa tempor convallis.', '2019-09-03', 43);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (318, 61, 46, 'Morbi quis tortor id nulla ultrices aliquet.', '2019-08-23', 34);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (319, 8, 96, 'Nullam sit amet turpis elementum ligula vehicula consequat.', '2019-02-20', 94);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (320, 17, 3, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', '2019-04-20', 41);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (321, 41, 43, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2019-01-28', 48);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (322, 58, 71, 'In quis justo.', '2018-12-29', 72);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (323, 61, 8, 'Donec posuere metus vitae ipsum.', '2019-10-13', 15);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (324, 82, 11, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2019-05-27', 37);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (325, 88, 4, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2019-03-06', 70);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (326, 54, 16, 'Pellentesque ultrices mattis odio.', '2019-11-07', 33);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (327, 91, 92, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2019-05-06', 89);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (328, 67, 43, 'Suspendisse accumsan tortor quis turpis.', '2019-10-27', 11);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (329, 96, 60, 'Praesent blandit lacinia erat.', '2018-12-09', 60);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (330, 97, 59, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.', '2019-04-04', 25);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (331, 57, 91, 'vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', '2019-04-29', 43);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (332, 55, 93, 'Aenean sit amet justo. Morbi ut odio.', '2019-05-24', 39);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (333, 93, 90, 'Fusce consequat.', '2019-05-11', 29);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (334, 2, 97, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2018-11-27', 19);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (335, 43, 41, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', '2019-02-25', 62);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (336, 38, 64, 'Curabitur convallis.', '2019-01-15', 34);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (337, 82, 82, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', '2019-10-28', 38);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (338, 58, 87, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '2018-12-14', 95);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (339, 40, 60, 'Suspendisse potenti. Nullam porttitor lacus at turpis.', '2018-11-24', 27);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (340, 45, 76, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2019-06-11', 13);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (341, 98, 97, 'Nullam varius.', '2019-08-12', 63);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (342, 78, 62, 'Suspendisse potenti. In eleifend quam a odio.', '2019-04-18', 64);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (343, 86, 7, 'Nam tristique tortor eu pede.', '2019-01-26', 38);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (344, 24, 97, 'Duis ac nibh.', '2019-04-06', 50);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (345, 38, 63, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2018-12-26', 72);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (346, 66, 65, 'Curabitur at ipsum ac tellus semper interdum.', '2019-03-30', 51);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (347, 18, 97, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '2019-04-01', 57);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (348, 49, 14, 'Maecenas rhoncus aliquam lacus.', '2019-03-02', 59);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (349, 94, 84, 'Sed sagittis.', '2019-06-27', 75);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (350, 17, 4, 'Donec quis orci eget orci vehicula condimentum.', '2019-01-24', 20);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (351, 76, 19, 'Sed vel enim sit amet nunc viverra dapibus.', '2019-10-30', 10);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (352, 41, 69, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', '2019-04-28', 8);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (353, 7, 92, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '2018-12-15', 2);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (354, 22, 94, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2019-06-20', 95);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (355, 91, 96, 'Duis at velit eu est congue elementum.', '2019-05-15', 40);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (356, 51, 67, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', '2019-01-19', 24);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (357, 3, 51, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', '2019-09-13', 78);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (358, 11, 80, 'Maecenas tincidunt lacus at velit.', '2019-10-08', 12);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (359, 80, 84, 'In eleifend quam a odio.', '2019-02-09', 34);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (360, 78, 37, 'Curabitur gravida nisi at nibh.', '2019-09-27', 87);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (361, 76, 57, 'Integer ac neque.', '2019-01-07', 21);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (362, 89, 50, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2019-01-21', 17);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (363, 24, 58, 'Praesent blandit. Nam nulla.', '2019-05-24', 25);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (364, 9, 32, 'Proin interdum mauris non ligula pellentesque ultrices.', '2019-08-18', 94);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (365, 12, 81, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', '2018-11-29', 62);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (366, 49, 63, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '2018-12-06', 84);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (367, 79, 56, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2019-02-25', 39);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (368, 91, 9, 'Proin eu mi.', '2019-01-09', 66);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (369, 30, 17, 'Cras pellentesque volutpat dui.', '2019-04-14', 89);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (370, 76, 4, 'Curabitur gravida nisi at nibh.', '2019-05-15', 40);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (371, 57, 98, 'Ut at dolor quis odio consequat varius. Integer ac leo.', '2019-02-21', 20);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (372, 97, 48, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.', '2019-07-30', 20);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (373, 25, 64, 'Nullam porttitor lacus at turpis.', '2019-09-01', 61);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (374, 42, 26, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2019-01-19', 83);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (375, 88, 66, 'Morbi vel lectus in quam fringilla rhoncus.', '2019-06-19', 71);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (376, 34, 85, 'Nullam sit amet turpis elementum ligula vehicula consequat.', '2019-02-23', 60);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (377, 37, 30, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2019-01-22', 66);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (378, 72, 95, 'Curabitur gravida nisi at nibh.', '2019-08-18', 34);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (379, 14, 82, 'Suspendisse potenti.', '2019-04-30', 92);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (380, 48, 5, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2019-01-27', 56);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (381, 72, 20, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2019-05-21', 38);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (382, 16, 10, 'Curabitur in libero ut massa volutpat convallis.', '2019-09-28', 32);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (383, 31, 47, 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', '2019-09-09', 92);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (384, 20, 5, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', '2019-08-16', 56);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (385, 14, 24, 'Aenean lectus. Pellentesque eget nunc.', '2019-04-12', 97);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (386, 4, 97, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2019-02-23', 30);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (387, 28, 7, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2019-05-05', 36);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (388, 1, 20, 'Duis ac nibh.', '2019-02-15', 8);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (389, 27, 63, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2019-08-16', 9);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (390, 93, 67, 'Suspendisse potenti.', '2019-08-25', 12);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (391, 48, 5, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '2019-07-21', 5);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (392, 32, 28, 'Vivamus tortor.', '2019-11-15', 44);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (393, 78, 12, 'Sed ante.', '2019-09-07', 33);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (394, 20, 11, 'Donec dapibus. Duis at velit eu est congue elementum.', '2019-09-14', 61);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (395, 95, 82, 'Nulla suscipit ligula in lacus.', '2019-03-25', 19);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (396, 3, 50, 'Nunc rhoncus dui vel sem.', '2019-07-22', 79);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (397, 3, 81, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2019-10-04', 66);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (398, 2, 43, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', '2018-11-25', 93);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (399, 44, 23, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.', '2019-03-30', 11);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (400, 68, 15, 'Donec semper sapien a libero. Nam dui.', '2019-01-19', 54);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (401, 97, 33, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', '2018-12-27', 52);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (402, 38, 88, 'Suspendisse potenti. In eleifend quam a odio.', '2019-05-23', 30);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (403, 98, 8, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', '2019-08-03', 28);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (404, 58, 99, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', '2019-04-24', 62);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (405, 84, 3, 'Nulla justo.', '2019-05-04', 6);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (406, 70, 83, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2019-06-17', 42);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (407, 20, 14, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', '2018-12-29', 8);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (408, 30, 36, 'Vivamus tortor.', '2019-05-10', 52);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (409, 44, 54, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2019-05-10', 78);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (410, 6, 57, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', '2019-04-13', 89);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (411, 15, 71, 'Praesent blandit. Nam nulla.', '2019-04-04', 100);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (412, 57, 13, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2019-09-06', 25);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (413, 69, 96, 'Aliquam erat volutpat.', '2019-10-16', 30);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (414, 93, 8, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2019-03-14', 48);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (415, 13, 51, 'Aliquam non mauris.', '2019-05-30', 62);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (416, 35, 13, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', '2019-04-11', 36);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (417, 97, 69, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', '2019-03-19', 45);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (418, 52, 43, 'Nunc purus.', '2019-10-19', 28);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (419, 9, 20, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '2019-08-12', 5);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (420, 19, 14, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2018-12-11', 35);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (421, 31, 41, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2019-01-31', 56);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (422, 29, 77, 'Duis bibendum.', '2019-04-27', 11);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (423, 87, 71, 'Etiam vel augue.', '2018-12-30', 90);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (424, 13, 47, 'Mauris lacinia sapien quis libero.', '2019-04-04', 88);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (425, 37, 83, 'Integer a nibh.', '2019-08-30', 33);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (426, 22, 39, 'Vivamus tortor.', '2019-06-29', 95);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (427, 31, 67, 'Sed ante. Vivamus tortor.', '2019-06-06', 71);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (428, 93, 93, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2018-11-29', 54);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (429, 50, 20, 'Curabitur in libero ut massa volutpat convallis.', '2019-08-20', 18);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (430, 79, 75, 'Etiam vel augue. Vestibulum rutrum rutrum neque.', '2019-08-11', 81);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (431, 47, 101, 'Nunc rhoncus dui vel sem. Sed sagittis.', '2019-01-23', 67);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (432, 14, 74, 'Morbi non quam nec dui luctus rutrum.', '2019-05-25', 15);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (433, 43, 48, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '2019-07-05', 10);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (434, 7, 94, 'Morbi vel lectus in quam fringilla rhoncus.', '2019-02-27', 4);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (435, 100, 100, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '2019-08-24', 76);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (436, 12, 41, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2019-10-31', 44);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (437, 60, 63, 'Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2019-05-05', 88);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (438, 39, 7, 'Duis mattis egestas metus.', '2019-02-19', 85);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (439, 27, 25, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', '2019-05-18', 21);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (440, 52, 11, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', '2019-09-14', 78);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (441, 39, 15, 'Suspendisse potenti. Nullam porttitor lacus at turpis.', '2018-12-28', 29);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (442, 58, 19, 'Praesent id massa id nisl venenatis lacinia.', '2019-06-17', 3);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (443, 89, 7, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2019-01-17', 54);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (444, 37, 13, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2019-10-01', 4);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (445, 92, 29, 'Nunc purus.', '2019-09-19', 67);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (446, 60, 53, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2019-02-15', 11);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (447, 64, 4, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', '2019-06-21', 18);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (448, 53, 23, 'Duis mattis egestas metus.', '2019-05-25', 81);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (449, 93, 45, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2019-01-19', 100);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (450, 3, 14, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '2019-05-03', 24);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (451, 38, 42, 'Sed accumsan felis.', '2019-09-02', 11);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (452, 92, 58, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2019-04-28', 69);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (453, 39, 37, 'Curabitur gravida nisi at nibh.', '2019-11-17', 88);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (454, 37, 15, 'Aliquam quis turpis eget elit sodales scelerisque.', '2019-03-23', 5);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (455, 67, 67, 'Maecenas rhoncus aliquam lacus.', '2019-06-30', 41);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (456, 20, 23, 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', '2019-07-10', 43);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (457, 42, 56, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2019-04-16', 16);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (458, 74, 33, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', '2019-06-14', 37);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (459, 8, 77, 'Pellentesque at nulla. Suspendisse potenti.', '2019-01-07', 88);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (460, 32, 5, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2018-12-14', 51);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (461, 26, 57, 'Praesent blandit.', '2019-04-06', 94);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (462, 36, 46, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', '2019-02-06', 64);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (463, 47, 6, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', '2019-08-21', 5);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (464, 22, 49, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2019-05-26', 84);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (465, 64, 29, 'Donec vitae nisi.', '2019-03-08', 60);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (466, 85, 96, 'In quis justo.', '2018-12-19', 36);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (467, 67, 26, 'Fusce posuere felis sed lacus.', '2019-09-04', 10);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (468, 91, 94, 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2019-01-24', 21);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (469, 58, 13, 'In hac habitasse platea dictumst.', '2019-02-18', 12);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (470, 83, 71, 'Fusce consequat. Nulla nisl.', '2019-11-07', 83);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (471, 70, 42, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2019-03-09', 88);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (472, 67, 83, 'Nulla tempus.', '2019-08-24', 8);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (473, 39, 98, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '2019-10-20', 73);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (474, 44, 34, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2019-02-13', 7);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (475, 81, 94, 'In hac habitasse platea dictumst.', '2019-11-15', 2);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (476, 61, 55, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', '2019-01-15', 35);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (477, 87, 35, 'Donec ut dolor.', '2018-12-20', 47);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (478, 97, 11, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2019-01-14', 85);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (479, 32, 95, 'Aliquam erat volutpat.', '2019-10-18', 76);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (480, 34, 26, 'Maecenas tincidunt lacus at velit.', '2019-10-13', 10);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (481, 75, 66, 'Etiam vel augue. Vestibulum rutrum rutrum neque.', '2018-12-05', 46);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (482, 19, 62, 'Praesent blandit.', '2019-10-12', 22);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (483, 13, 18, 'Morbi ut odio.', '2019-07-18', 4);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (484, 50, 33, 'Phasellus sit amet erat. Nulla tempus.', '2019-05-18', 59);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (485, 62, 43, 'Aenean lectus. Pellentesque eget nunc.', '2019-07-05', 10);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (486, 64, 45, 'Nunc purus.', '2018-11-26', 95);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (487, 71, 92, 'Donec posuere metus vitae ipsum.', '2019-11-16', 56);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (488, 2, 100, 'Sed sagittis.', '2019-03-25', 11);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (489, 58, 74, 'Duis aliquam convallis nunc.', '2018-12-19', 51);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (490, 27, 64, 'In sagittis dui vel nisl. Duis ac nibh.', '2018-12-09', 97);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (491, 83, 80, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2019-02-19', 11);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (492, 70, 28, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2019-10-17', 46);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (493, 49, 87, 'Etiam faucibus cursus urna.', '2019-07-18', 84);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (494, 9, 67, 'Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2019-08-02', 59);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (495, 92, 39, 'Etiam vel augue. Vestibulum rutrum rutrum neque.', '2019-06-21', 98);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (496, 67, 42, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '2019-02-06', 51);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (497, 31, 62, 'Morbi ut odio.', '2019-09-17', 23);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (498, 90, 93, 'In hac habitasse platea dictumst.', '2019-03-07', 79);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (499, 86, 16, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '2019-06-20', 43);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (500, 98, 30, 'In sagittis dui vel nisl.', '2019-01-27', 3);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (501, 18, 7, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2019-06-12', 87);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (502, 4, 34, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2019-02-15', 96);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (503, 96, 2, 'Curabitur convallis.', '2019-08-16', 98);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (504, 86, 3, 'Nunc nisl.', '2018-12-12', 66);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (505, 4, 11, 'Maecenas rhoncus aliquam lacus.', '2018-12-26', 93);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (506, 70, 45, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', '2019-05-11', 4);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (507, 99, 30, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2018-11-25', 10);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (508, 18, 56, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', '2019-05-22', 62);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (509, 80, 63, 'Donec dapibus.', '2019-05-07', 10);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (510, 9, 15, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2019-05-17', 7);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (511, 83, 57, 'Donec semper sapien a libero. Nam dui.', '2019-02-13', 19);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (512, 56, 53, 'Maecenas rhoncus aliquam lacus.', '2019-06-29', 86);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (513, 74, 58, 'In hac habitasse platea dictumst.', '2019-03-03', 59);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (514, 34, 101, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '2019-01-09', 3);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (515, 68, 93, 'Vestibulum sed magna at nunc commodo placerat.', '2019-01-18', 2);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (516, 92, 85, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', '2019-07-28', 49);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (517, 54, 67, 'Mauris sit amet eros.', '2019-10-19', 12);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (518, 29, 99, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2019-10-10', 49);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (519, 75, 35, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2018-12-03', 19);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (520, 15, 87, 'Suspendisse ornare consequat lectus.', '2019-06-02', 67);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (521, 16, 14, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', '2019-08-21', 42);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (522, 13, 32, 'Nunc nisl.', '2019-07-10', 84);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (523, 50, 2, 'Integer ac leo. Pellentesque ultrices mattis odio.', '2018-11-25', 63);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (524, 25, 22, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', '2019-04-07', 61);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (525, 89, 2, 'Phasellus id sapien in sapien iaculis congue.', '2019-09-21', 37);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (526, 23, 39, 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2019-09-29', 66);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (527, 66, 94, 'Proin at turpis a pede posuere nonummy.', '2019-08-12', 45);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (528, 57, 39, 'Nulla justo.', '2019-04-15', 99);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (529, 9, 5, 'Duis ac nibh.', '2019-04-15', 74);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (530, 15, 22, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2018-11-27', 90);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (531, 25, 8, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2019-07-04', 69);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (532, 73, 45, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.', '2019-03-05', 27);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (533, 11, 82, 'Morbi vel lectus in quam fringilla rhoncus.', '2019-03-02', 87);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (534, 50, 84, 'In congue.', '2019-09-15', 64);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (535, 92, 71, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', '2019-01-05', 85);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (536, 78, 8, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '2018-12-29', 82);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (537, 53, 59, 'Morbi non quam nec dui luctus rutrum.', '2019-08-18', 84);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (538, 69, 32, 'Nullam varius. Nulla facilisi.', '2019-09-08', 45);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (539, 49, 22, 'Nulla tellus. In sagittis dui vel nisl.', '2019-01-30', 49);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (540, 66, 77, 'Donec posuere metus vitae ipsum.', '2019-01-09', 31);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (541, 97, 11, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', '2019-03-09', 83);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (542, 69, 30, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2019-01-27', 2);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (543, 47, 58, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', '2019-08-16', 53);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (544, 63, 4, 'Fusce consequat.', '2019-03-10', 31);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (545, 79, 54, 'Suspendisse potenti. In eleifend quam a odio.', '2019-08-08', 57);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (546, 40, 63, 'Aenean auctor gravida sem.', '2019-01-24', 48);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (547, 74, 46, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', '2019-08-18', 28);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (548, 93, 8, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2019-02-12', 67);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (549, 98, 95, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', '2019-04-18', 33);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (550, 27, 19, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', '2019-09-28', 100);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (551, 21, 26, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2019-08-15', 100);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (552, 44, 49, 'Integer a nibh.', '2019-07-20', 18);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (553, 69, 91, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2019-11-13', 47);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (554, 23, 59, 'Duis ac nibh.', '2019-03-12', 75);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (555, 30, 21, 'Nulla tellus.', '2019-04-22', 69);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (556, 15, 72, 'Donec semper sapien a libero.', '2019-09-04', 77);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (557, 67, 65, 'Integer a nibh. In quis justo.', '2019-03-24', 69);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (558, 10, 23, 'Aenean sit amet justo.', '2019-01-15', 91);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (559, 17, 96, 'Duis ac nibh.', '2019-03-02', 74);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (560, 65, 6, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2019-01-17', 97);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (561, 69, 62, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '2019-11-07', 96);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (562, 47, 28, 'Maecenas rhoncus aliquam lacus.', '2019-03-16', 61);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (563, 63, 35, 'Nulla justo.', '2019-01-05', 74);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (564, 99, 47, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', '2019-03-11', 71);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (565, 2, 14, 'Pellentesque ultrices mattis odio.', '2019-03-13', 8);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (566, 18, 7, 'Proin eu mi. Nulla ac enim.', '2019-10-22', 29);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (567, 48, 8, 'Nulla nisl.', '2019-09-25', 61);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (568, 18, 60, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2019-03-04', 45);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (569, 11, 16, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2019-03-29', 57);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (570, 17, 91, 'Vivamus in felis eu sapien cursus vestibulum.', '2019-08-09', 5);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (571, 70, 65, 'Sed sagittis.', '2019-07-16', 66);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (572, 93, 94, 'Phasellus in felis.', '2019-04-02', 55);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (573, 82, 68, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', '2019-07-15', 70);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (574, 88, 49, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2019-10-30', 83);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (575, 66, 89, 'Cras pellentesque volutpat dui.', '2019-09-26', 76);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (576, 37, 21, 'Duis aliquam convallis nunc.', '2019-10-28', 15);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (577, 74, 48, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2018-12-03', 12);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (578, 3, 72, 'Duis at velit eu est congue elementum.', '2019-10-27', 76);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (579, 80, 54, 'Donec dapibus. Duis at velit eu est congue elementum.', '2019-10-22', 90);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (580, 3, 45, 'Integer a nibh. In quis justo.', '2019-08-29', 65);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (581, 96, 74, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2019-01-03', 79);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (582, 21, 73, 'Etiam faucibus cursus urna. Ut tellus.', '2019-08-27', 69);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (583, 68, 63, 'Suspendisse ornare consequat lectus.', '2019-04-30', 44);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (584, 74, 92, 'Nullam molestie nibh in lectus.', '2019-10-29', 53);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (585, 15, 95, 'Suspendisse accumsan tortor quis turpis. Sed ante.', '2019-07-20', 98);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (586, 41, 63, 'Nulla nisl.', '2019-08-27', 62);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (587, 16, 42, 'Cras pellentesque volutpat dui.', '2019-09-20', 66);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (588, 36, 60, 'Vivamus tortor. Duis mattis egestas metus.', '2018-12-28', 55);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (589, 47, 53, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', '2019-03-13', 33);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (590, 17, 30, 'Cras in purus eu magna vulputate luctus.', '2019-04-06', 74);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (591, 100, 15, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2019-02-02', 36);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (592, 10, 67, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2019-07-10', 17);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (593, 50, 94, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2019-04-28', 12);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (594, 77, 3, 'Donec posuere metus vitae ipsum. Aliquam non mauris.', '2018-11-21', 59);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (595, 95, 77, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2019-04-22', 47);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (596, 90, 2, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', '2019-05-27', 70);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (597, 92, 55, 'Nam dui.', '2019-01-07', 46);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (598, 69, 60, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2019-09-02', 24);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (599, 65, 3, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', '2019-10-13', 57);
insert into comment (id, comment_parent_id, account_id, content, created, product_id) values (600, 56, 94, 'Proin eu mi.', '2019-08-21', 7);
